### ISSUE TITLE
Exception in thread

### ISSUE THREAD

**Issue by lurens** [dvitsios/mirnovo#2]
Hi
I am trying to run mirnovo on the test dataset, but i get the following error:

Exception in thread Thread-34:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "get_genomic_features.py", line 31, in run
    getFeaturesForCluster(self.threadID, self.q)
  File "get_genomic_features.py", line 48, in getFeaturesForCluster
    ret_list = get_genomic_features(cluster_number)
  File "get_genomic_features.py", line 216, in get_genomic_features
    out = subprocess.check_output(cmd, shell = True)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'echo ACCTGGCGCtaaaccattcgtagacgacctgctTCTGGGTCGGGGTTTCGTACGTAGCAGAGCAGCTCCCTCGCTGCGATCTATTGAAAG | util/RNAfold --noPS 2>/dev/null' returned non-zero exit status 127

Have you an idea on how to solve it?
Thank you in advance
lorenzo

**Comment by dvitsios** [comment]
Hi,
have you tried analysing your sample through the web-app? Does it finish successfully or do you get similar exception errors?
D

**Comment by lurens** [comment]
Yes, it works. Unfortunately I am working on a genome which is still not available on the web-app and the only solution is at the moment to run it on my PC

**Comment by dvitsios** [comment]
I assume you have followed the instructions below for installing your custom genome, right?
http://wwwdev.ebi.ac.uk/enright-dev/mirnovo-standalone-pkg/Genome-Annotation-1.0/README

Alternatively, if the genome you are interested in is publicly available I could add it to mirnovo's web-app.

**Comment by godkin1211** [comment]
Hi, 
when I run the basic example `./mirnovo.pl -i ../example_file.tallied.gz -g hsa -t hsa -o example_run` after downloading hsa genome and training model, I also got the same error.

The python version I use is **2.7.12**.

How do I solve this problem? Thank you very much!
